name: "Composer Package Bump"
description: "Bump composer packages based on version (dev or release)"

inputs:
    packages:
        description: "JSON array of packages with their dev versions (e.g., '[{\"name\":\"pylesoft/package\",\"dev\":\"dev-main\"}]')"
        required: true
    version:
        description: "Version to use: 'dev' for dev versions, or release version like '2025.50.0'"
        required: false
        default: "dev"
    php-version:
        description: "PHP version to use (e.g., '8.1', '8.2', '8.3')"
        required: false
        default: "8.3"
    update-lock:
        description: "Whether to run composer update for the changed packages"
        required: false
        default: "true"
    composer-auth:
        description: "JSON object with composer authentication config"
        required: false
        default: ""
    commit:
        description: "Whether to commit the changes"
        required: false
        default: "true"
    commit-message:
        description: "Commit message"
        required: false
        default: "chore: bump composer packages"

runs:
    using: "composite"
    steps:
        - name: Setup PHP
          if: ${{ inputs.update-lock == 'true' }}
          uses: shivammathur/setup-php@v2
          with:
              php-version: ${{ inputs.php-version }}
              tools: composer:v2

        - name: Configure Composer Authentication
          if: ${{ inputs.update-lock == 'true' && inputs.composer-auth != '' }}
          shell: bash
          run: |
              echo "🔐 Configuring composer authentication..."
              
              # Parse JSON auth config and apply each entry
              AUTH_CONFIG='${{ inputs.composer-auth }}'
              
              # Validate JSON first
              if ! echo "$AUTH_CONFIG" | jq empty 2>/dev/null; then
                  echo "❌ Invalid JSON in composer-auth"
                  exit 1
              fi
              
              echo "$AUTH_CONFIG" | jq -r 'to_entries[] | @base64' | while read -r entry; do
                  # Decode the entry
                  _jq() {
                      echo "$entry" | base64 --decode | jq -r "$1"
                  }
                  
                  DOMAIN=$(_jq '.key')
                  TYPE=$(_jq '.value.type // "http-basic"')
                  USERNAME=$(_jq '.value.username // "token"')
                  PASSWORD=$(_jq '.value.password')
                  GLOBAL=$(_jq '.value.global // false')
                  
                  if [[ "$TYPE" == "http-basic" ]]; then
                      if [[ "$GLOBAL" == "true" ]]; then
                          composer config --global --auth "http-basic.$DOMAIN" "$USERNAME" "$PASSWORD"
                          echo "  ✓ Configured $DOMAIN (global)"
                      else
                          composer config "http-basic.$DOMAIN" "$USERNAME" "$PASSWORD"
                          echo "  ✓ Configured $DOMAIN"
                      fi
                  elif [[ "$TYPE" == "github-oauth" ]]; then
                      composer config --global github-oauth.github.com "$PASSWORD"
                      echo "  ✓ Configured GitHub OAuth"
                  fi
              done

        - name: Bump composer packages
          shell: bash
          run: |
              PACKAGES='${{ inputs.packages }}'
              VERSION="${{ inputs.version }}"
              
              echo "📦 Bumping composer packages..."
              
              # Validate packages JSON
              if ! echo "$PACKAGES" | jq empty 2>/dev/null; then
                  echo "❌ Invalid JSON in packages"
                  exit 1
              fi
              
              # Clear/create the file
              > /tmp/updated_packages.txt
              
              # Determine target version mode
              if [[ -z "$VERSION" ]] || [[ "$VERSION" == "dev" ]] || [[ "$VERSION" == "null" ]]; then
                  echo "🔧 Dev mode: Using dev versions"
                  TARGET_MODE="dev"
              elif [[ "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
                  BRANCH_VERSION="${VERSION%.*}.x"
                  echo "🚀 Release mode: Using branch version $BRANCH_VERSION"
                  TARGET_MODE="release"
              else
                  echo "⚠️ Invalid version format: $VERSION (using dev mode)"
                  TARGET_MODE="dev"
              fi
              
              # Process each package (avoiding subshell issue with while loop)
              PACKAGE_COUNT=$(echo "$PACKAGES" | jq 'length')
              for i in $(seq 0 $((PACKAGE_COUNT - 1))); do
                  PACKAGE=$(echo "$PACKAGES" | jq -r ".[$i]")
                  PACKAGE_NAME=$(echo "$PACKAGE" | jq -r '.name')
                  DEV_VERSION=$(echo "$PACKAGE" | jq -r '.dev // "dev-main"')
                  
                  if [[ "$TARGET_MODE" == "dev" ]]; then
                      TARGET_VERSION="$DEV_VERSION"
                  else
                      TARGET_VERSION="$BRANCH_VERSION"
                  fi
                  
                  echo "  → Updating $PACKAGE_NAME to $TARGET_VERSION"
                  
                  # Update composer.json
                  jq --arg name "$PACKAGE_NAME" --arg version "$TARGET_VERSION" \
                     '.require[$name] = $version' composer.json > composer.json.tmp
                  
                  # Check if jq succeeded
                  if [[ $? -ne 0 ]]; then
                      echo "❌ Failed to update composer.json"
                      exit 1
                  fi
                  
                  mv composer.json.tmp composer.json
                  
                  # Add to list for composer update
                  echo "$PACKAGE_NAME" >> /tmp/updated_packages.txt
              done
              
              echo "✅ composer.json updated"

        - name: Update composer.lock
          if: ${{ inputs.update-lock == 'true' }}
          shell: bash
          run: |
              echo "🔄 Updating composer.lock..."
              
              # Configure GitHub token if available (for rate limiting)
              if [[ -n "${{ github.token }}" ]]; then
                  composer config --global github-oauth.github.com "${{ github.token }}"
              fi
              
              # Check if packages file exists and has content
              if [[ -f /tmp/updated_packages.txt ]] && [[ -s /tmp/updated_packages.txt ]]; then
                  PACKAGES_TO_UPDATE=$(cat /tmp/updated_packages.txt | tr '\n' ' ')
                  
                  echo "  Updating packages: $PACKAGES_TO_UPDATE"
                  
                  # Run composer update with error handling
                  if composer update $PACKAGES_TO_UPDATE --no-install --no-scripts; then
                      echo "✅ composer.lock updated"
                  else
                      echo "❌ Failed to update composer.lock"
                      exit 1
                  fi
              else
                  echo "⚠️ No packages to update"
              fi

        - name: Commit changes
          if: ${{ inputs.commit == 'true' }}
          shell: bash
          run: |
              # Check for changes (using || to handle missing files)
              if git status --porcelain composer.json composer.lock 2>/dev/null | grep -q .; then
                  git config user.name "github-actions[bot]"
                  git config user.email "github-actions[bot]@users.noreply.github.com"
                  
                  # Add files that exist
                  git add composer.json
                  if [[ -f composer.lock ]]; then
                      git add composer.lock
                  fi
                  
                  # Build commit message
                  VERSION="${{ inputs.version }}"
                  if [[ -z "$VERSION" ]] || [[ "$VERSION" == "dev" ]] || [[ "$VERSION" == "null" ]]; then
                      COMMIT_MSG="${{ inputs.commit-message }} (dev versions)"
                  else
                      COMMIT_MSG="${{ inputs.commit-message }} (version $VERSION)"
                  fi
                  
                  git commit -m "$COMMIT_MSG"
                  git push
                  echo "✅ Changes committed"
              else
                  echo "ℹ️ No changes to commit"
              fi
