name: "Composer Package Bump"
description: "Bump composer packages based on version (dev or release)"

inputs:
    packages:
        description: "JSON array of packages with their dev versions (e.g., '[{\"name\":\"pylesoft/package\",\"dev\":\"dev-main\"}]')"
        required: true
    version:
        description: "Version to use: 'dev' for dev versions, or release version like '2025.50.0'"
        required: false
        default: "dev"
    update-lock:
        description: "Whether to run composer update for the changed packages"
        required: false
        default: "true"
    commit:
        description: "Whether to commit the changes"
        required: false
        default: "true"
    commit-message:
        description: "Commit message"
        required: false
        default: "chore: bump composer packages"

runs:
    using: "composite"
    steps:
        - name: Setup PHP
          if: ${{ inputs.update-lock == 'true' }}
          uses: shivammathur/setup-php@v2
          with:
              php-version: '8.3'
              tools: composer:v2

        - name: Bump composer packages
          shell: bash
          run: |
              PACKAGES='${{ inputs.packages }}'
              VERSION="${{ inputs.version }}"
              
              echo "📦 Bumping composer packages..."
              
              # Determine target version mode
              if [[ -z "$VERSION" ]] || [[ "$VERSION" == "dev" ]] || [[ "$VERSION" == "null" ]]; then
                  echo "🔧 Dev mode: Using dev versions"
                  TARGET_MODE="dev"
              elif [[ "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
                  BRANCH_VERSION="${VERSION%.*}.x"
                  echo "🚀 Release mode: Using branch version $BRANCH_VERSION"
                  TARGET_MODE="release"
              else
                  echo "⚠️ Invalid version format: $VERSION (using dev mode)"
                  TARGET_MODE="dev"
              fi
              
              # Track updated packages for composer update
              UPDATED_PACKAGES=""
              
              # Parse JSON and update each package
              echo "$PACKAGES" | jq -c '.[]' | while read -r package; do
                  PACKAGE_NAME=$(echo "$package" | jq -r '.name')
                  DEV_VERSION=$(echo "$package" | jq -r '.dev // "dev-main"')
                  
                  if [[ "$TARGET_MODE" == "dev" ]]; then
                      TARGET_VERSION="$DEV_VERSION"
                  else
                      TARGET_VERSION="$BRANCH_VERSION"
                  fi
                  
                  echo "  → Updating $PACKAGE_NAME to $TARGET_VERSION"
                  
                  # Update composer.json
                  jq --arg name "$PACKAGE_NAME" --arg version "$TARGET_VERSION" \
                     '.require[$name] = $version' composer.json > composer.json.tmp
                  mv composer.json.tmp composer.json
                  
                  # Add to list for composer update
                  echo "$PACKAGE_NAME" >> /tmp/updated_packages.txt
              done
              
              echo "✅ composer.json updated"

        - name: Update composer.lock
          if: ${{ inputs.update-lock == 'true' }}
          shell: bash
          run: |
              echo "🔄 Updating composer.lock..."
              
              # Read the list of updated packages
              if [[ -f /tmp/updated_packages.txt ]]; then
                  PACKAGES_TO_UPDATE=$(cat /tmp/updated_packages.txt | tr '\n' ' ')
                  
                  # Configure composer to use GitHub token if available
                  if [[ -n "${{ github.token }}" ]]; then
                      composer config --global github-oauth.github.com "${{ github.token }}"
                  fi
                  
                  # Update only the changed packages (faster than full update)
                  echo "  Running: composer update $PACKAGES_TO_UPDATE --no-install"
                  composer update $PACKAGES_TO_UPDATE --no-install --no-scripts
                  
                  echo "✅ composer.lock updated"
              else
                  echo "⚠️ No packages to update"
              fi

        - name: Commit changes
          if: ${{ inputs.commit == 'true' }}
          shell: bash
          run: |
              # Check for changes in both files
              if [[ -n $(git status -s composer.json composer.lock) ]]; then
                  git config user.name "github-actions[bot]"
                  git config user.email "github-actions[bot]@users.noreply.github.com"
                  
                  # Add both files
                  git add composer.json
                  if [[ -f composer.lock ]]; then
                      git add composer.lock
                  fi
                  
                  # Enhanced commit message
                  VERSION="${{ inputs.version }}"
                  if [[ -z "$VERSION" ]] || [[ "$VERSION" == "dev" ]] || [[ "$VERSION" == "null" ]]; then
                      COMMIT_MSG="${{ inputs.commit-message }} (dev versions)"
                  else
                      COMMIT_MSG="${{ inputs.commit-message }} (version $VERSION)"
                  fi
                  
                  git commit -m "$COMMIT_MSG"
                  git push
                  echo "✅ Changes committed (composer.json + composer.lock)"
              else
                  echo "ℹ️ No changes to commit"
              fi
